apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbeye-http-server
  namespace: mbeye-app
  labels:
    app: mbeye-http-server
spec:
  selector:
    matchLabels:
        app: mbeye-http-server
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mbeye-http-server
    spec:
      containers:
        - name: mbeye-http-server
          image: 633706706076.dkr.ecr.us-east-1.amazonaws.com/mb-eye:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always